jwt:
  signing-key: ${JWT_SIGNING_KEY}
  expiration: ${JWT_EXPIRATION:86400000}

forex:
  api:
    key: ${FOREX_API_KEY}
    url: "https://openexchangerates.org/api/latest.json?app_id={app_id}&symbols=EUR,BGN"
    base: "USD"

mail:
  expenseTracker: "expensetracker@example.com"
  host: localhost
  port: 1025
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}

spring:
  application:
    name: expense-tracker
  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: none
    properties: {}
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/expense_tracker?createDatabaseIfNotExist=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:demo-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:demo-client-secret}
            scope: openid,profile,email

server:
  port: 8080
