jwt:
  signing-key: dev-secret-change-me-32-bytes-min-123456
  expiration: 86400000

forex:
  api:
    key: demo

mail:
  username: test
  password: test

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security.authentication: DEBUG
    com.example.expense_tracker: DEBUG
    com.example.expense_tracker.service.impl.BudgetServiceImpl: DEBUG
