jwt:
  signing-key: ${JWT_SIGNING_KEY:mySecretKey123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000}

mail:
  expenseTracker: "expensetracker@example.com"
  host: localhost
  port: 1025
  username: ${MAIL_USERNAME:test}
  password: ${MAIL_PASSWORD:test}

spring:
  application:
    name: expense-tracker
  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/expense_tracker?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:12345}
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: user:email

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security.authentication: DEBUG
    com.example.expense_tracker: DEBUG