jwt:
  signing-key: ${JWT_SIGNING_KEY:mySecretKey123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000}

forex:
  api:
    key: ${FOREX_API_KEY:c92e55f7de3d4bb8bbd3d22241bb1755}
    url: "https://openexchangerates.org/api/latest.json?app_id={app_id}&symbols=EUR,BGN"
    base: "USD"

mail:
  expenseTracker: "expensetracker@example.com"
  host: localhost
  port: 1025
  username: ${MAIL_USERNAME:test}
  password: ${MAIL_PASSWORD:test}

spring:
  application:
    name: expense-tracker
  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/expense_tracker?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:12345}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security.authentication: DEBUG
    com.example.expense_tracker: DEBUG
    com.example.expense_tracker.service.impl.BudgetServiceImpl: DEBUG
